**Testing the Model**

In [ ]:
# Importung Library
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.preprocessing.image import load_img, img_to_array

# Load the model
model = load_model('/content/FINAL.keras')

# Function to preprocess the image
def preprocess_image(image_path, target_size):
    img = load_img(image_path, target_size=target_size)
    img_array = img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension
    img_array = preprocess_input(img_array)  # MobileNetV2 specific preprocessing
    return (img_array+1)/2*255

# Path to your test image and target size for the model
image_path = '/content/paper295.jpg'
target_size = (224, 224)  # MobileNetV2 input size
test_image = preprocess_image(image_path, target_size)
test_image = (test_image+1)/2
# Make predictions
predictions = model.predict(test_image)
predicted_class = np.argmax(predictions, axis=-1)

# Decode predictions
class_labels = ['HDPE', 'LDPE', 'PET', 'PP', 'PS', 'PVC', 'glass', 'metal', 'other', 'paper']  # Replace with your actual class labels
predicted_label = class_labels[predicted_class[0]]
print(f'Predicted label: {predicted_label}')


1/1 [==============================] - 1s 830ms/step
Predicted label: paper


In [ ]:
print(test_image)

[[[[116.5 116.5 116.5]
   [117.  117.  117. ]
   [117.5 117.5 117.5]
   ...
   [ 89.5  89.5  89.5]
   [ 89.   89.   89. ]
   [ 88.5  88.5  88.5]]

  [[116.5 116.5 116.5]
   [117.  117.  117. ]
   [117.  117.  117. ]
   ...
   [ 89.5  89.5  89.5]
   [ 89.   89.   89. ]
   [ 88.5  88.5  88.5]]

  [[117.  117.  117. ]
   [117.  117.  117. ]
   [117.  117.  117. ]
   ...
   [ 89.5  89.5  89.5]
   [ 89.   89.   89. ]
   [ 88.5  88.5  88.5]]

  ...

  [[ 95.   93.   91.5]
   [ 95.5  93.5  92. ]
   [ 95.   93.   91.5]
   ...
   [ 71.   70.5  68.5]
   [ 70.5  70.   68. ]
   [ 70.   69.5  67.5]]

  [[ 95.5  93.5  92. ]
   [ 96.   94.   92.5]
   [ 95.   93.   91.5]
   ...
   [ 71.   70.5  68.5]
   [ 70.5  70.   68. ]
   [ 70.   69.5  67.5]]

  [[ 96.   94.   92.5]
   [ 96.   94.   92.5]
   [ 95.5  93.5  92. ]
   ...
   [ 71.   70.5  68.5]
   [ 70.5  70.   68. ]
   [ 70.   69.5  67.5]]]]
